2021-05-24 23:46:32.018945: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2021-05-24 23:46:32.066307: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2593575000 Hz
2021-05-24 23:46:32.068497: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55742d7b0ea0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-05-24 23:46:32.068570: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-05-24 23:46:32.068775: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
WARNING:tensorflow:From ../../nets/model_evaluator.py:19: Model.evaluate_generator (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
Please use Model.evaluate, which supports generators.
2021-05-25 00:18:00.657851: W tensorflow/core/framework/op_kernel.cc:1741] Invalid argument: TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was (tf.float32, tf.float32), but the yielded element was (None,).
Traceback (most recent call last):

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 791, in generator_py_func
    flattened_values = nest.flatten_up_to(output_types, values)

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 396, in flatten_up_to
    assert_shallow_structure(shallow_tree, input_tree)

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 308, in assert_shallow_structure
    raise ValueError(

ValueError: The two structures don't have the same sequence length. Input structure has length 1, while shallow structure has length 2.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 243, in __call__
    ret = func(*args)

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
    return func(*args, **kwargs)

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 793, in generator_py_func
    six.reraise(TypeError, TypeError(

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 791, in generator_py_func
    flattened_values = nest.flatten_up_to(output_types, values)

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 396, in flatten_up_to
    assert_shallow_structure(shallow_tree, input_tree)

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 308, in assert_shallow_structure
    raise ValueError(

TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was (tf.float32, tf.float32), but the yielded element was (None,).


Traceback (most recent call last):
  File "../../nets/model_evaluator.py", line 26, in <module>
    main()
  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "../../nets/model_evaluator.py", line 19, in main
    scores = model.evaluate_generator(test_generator, verbose=0)
  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1500, in evaluate_generator
    return self.evaluate(
  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1081, in evaluate
    tmp_logs = test_function(iterator)
  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 611, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1661, in _filtered_call
    return self._call_flat(
  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1745, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 593, in call
    outputs = execute.execute(
  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was (tf.float32, tf.float32), but the yielded element was (None,).
Traceback (most recent call last):

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 791, in generator_py_func
    flattened_values = nest.flatten_up_to(output_types, values)

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 396, in flatten_up_to
    assert_shallow_structure(shallow_tree, input_tree)

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 308, in assert_shallow_structure
    raise ValueError(

ValueError: The two structures don't have the same sequence length. Input structure has length 1, while shallow structure has length 2.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/ops/script_ops.py", line 243, in __call__
    ret = func(*args)

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 309, in wrapper
    return func(*args, **kwargs)

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 793, in generator_py_func
    six.reraise(TypeError, TypeError(

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 791, in generator_py_func
    flattened_values = nest.flatten_up_to(output_types, values)

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 396, in flatten_up_to
    assert_shallow_structure(shallow_tree, input_tree)

  File "/home/e14317/.conda/envs/mphilenv/lib/python3.8/site-packages/tensorflow/python/data/util/nest.py", line 308, in assert_shallow_structure
    raise ValueError(

TypeError: `generator` yielded an element that did not match the expected structure. The expected structure was (tf.float32, tf.float32), but the yielded element was (None,).


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_test_function_8644]

Function call stack:
test_function

